# Generated by Django 3.2.5 on 2021-08-01 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Elementos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Triband',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('solucao', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='produtos')),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('elementos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btelecomapp.elementos')),
            ],
        ),
        migrations.CreateModel(
            name='Quadband',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('solucao', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='produtos')),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('elementos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btelecomapp.elementos')),
            ],
        ),
        migrations.CreateModel(
            name='Hexaband',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('solucao', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='produtos')),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('elementos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btelecomapp.elementos')),
            ],
        ),
        migrations.CreateModel(
            name='Dualband',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('solucao', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='produtos')),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('elementos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btelecomapp.elementos')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('data_on', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
