# Generated by Django 3.2.5 on 2021-08-16 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btelecomapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singleband',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('solucao', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='produtos')),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('elementos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btelecomapp.elementos')),
            ],
        ),
        migrations.CreateModel(
            name='Fiveband',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('solucao', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='produtos')),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('elementos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btelecomapp.elementos')),
            ],
        ),
    ]
