# Generated by Django 3.2.5 on 2021-08-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btelecomapp', '0002_fiveband_singleband'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solucoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('elementos', models.CharField(choices=[('Crossconennect', 'Crossconennect'), ('Mimo', 'Mimo'), ('Diplexer', 'Diplexer'), ('Triplexer', 'Triplexer'), ('Quadriplexer', 'Quadriplexer'), ('Mixmode', 'Mixmode'), ('Powersplit', 'Powersplit'), ('Radio Compartilhada', 'Radio Compartilhada'), ('Mais Elementos', 'Mais Elementos')], max_length=50)),
                ('portas', models.PositiveIntegerField()),
                ('descricao', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='produtos')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dualband',
            name='elementos',
        ),
        migrations.RemoveField(
            model_name='fiveband',
            name='elementos',
        ),
        migrations.RemoveField(
            model_name='hexaband',
            name='elementos',
        ),
        migrations.RemoveField(
            model_name='quadband',
            name='elementos',
        ),
        migrations.RemoveField(
            model_name='singleband',
            name='elementos',
        ),
        migrations.RemoveField(
            model_name='triband',
            name='elementos',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Dualband',
        ),
        migrations.DeleteModel(
            name='Elementos',
        ),
        migrations.DeleteModel(
            name='Fiveband',
        ),
        migrations.DeleteModel(
            name='Hexaband',
        ),
        migrations.DeleteModel(
            name='Quadband',
        ),
        migrations.DeleteModel(
            name='Singleband',
        ),
        migrations.DeleteModel(
            name='Triband',
        ),
    ]
